#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 20 12:24:01 2025

@author: caracterisation
"""
# analyse_bh_fenetre.py

from PyQt5 import QtCore, QtGui, QtWidgets
from mplwidget import MplWidget

class Ui_analyse(object):
  def setupUi(self, analyse_fft_bh):
    analyse_fft_bh.setObjectName("analyse_fft_bh")
    analyse_fft_bh.resize(1500, 2000)
    
    self.clear_button = QtWidgets.QPushButton(analyse_fft_bh)
    self.clear_button.setGeometry(QtCore.QRect(1300, 200, 181, 25))
    self.clear_button.setObjectName("clear_button")
    
    self.toolButton_Save = QtWidgets.QPushButton(analyse_fft_bh)
    self.toolButton_Save.setGeometry(QtCore.QRect(1300, 320, 181, 25))
    self.toolButton_Save.setObjectName("toolButton_Save")
    
    self.label_Harmo = QtWidgets.QLabel(analyse_fft_bh)
    self.label_Harmo.setGeometry(QtCore.QRect(1050, 360, 220, 25))
    self.label_Harmo.setObjectName("label_10")
    
    self.Harmo_spin=QtWidgets.QSpinBox(analyse_fft_bh)
    self.Harmo_spin.setGeometry(QtCore.QRect(1300, 360, 181, 25))
    self.Start_filtrage_button = QtWidgets.QPushButton(analyse_fft_bh)
    self.Start_filtrage_button.setGeometry(QtCore.QRect(1300, 400, 181, 25))
    self.Start_filtrage_button.setObjectName("Start_filtrage")
    
    #self.Harmo_spin = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.Harmo_spin.sizePolicy().hasHeightForWidth())
    self.Harmo_spin.setSizePolicy(sizePolicy)
    self.Harmo_spin.setAlignment(QtCore.Qt.AlignCenter)
    self.Harmo_spin.setMaximum(999999)
    self.Harmo_spin.setObjectName("Harmo_spin")
    
    self.widget_H = MplWidget(analyse_fft_bh)
    self.widget_H.setGeometry(QtCore.QRect(10, 10, 500, 500))
    self.widget_H.setObjectName("widget_H")
    
    self.widget_analyse_2 = MplWidget(analyse_fft_bh)
    self.widget_analyse_2.setGeometry(QtCore.QRect(550, 10, 500, 500))
    self.widget_analyse_2.setObjectName("widget_analyse_2")
    
    self.widget_analyse = MplWidget(analyse_fft_bh)
    self.widget_analyse.setGeometry(QtCore.QRect(10, 500, 600, 600))
    self.widget_analyse.setObjectName("widget_analyse")

    self.gridLayoutWidget = QtWidgets.QWidget(analyse_fft_bh)
    self.gridLayoutWidget.setGeometry(QtCore.QRect(600, 700, 471, 346))
    self.gridLayoutWidget.setObjectName("gridLayoutWidget")
    self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
    self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
    self.gridLayout.setContentsMargins(0, 0, 0, 0)
    self.gridLayout.setObjectName("gridLayout")
    
    
    self.label_Titre_brut = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Titre_brut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Titre_brut.setObjectName("label_Titre_brut")
    self.gridLayout.addWidget(self.label_Titre_brut, 0, 1, 1, 1)
    self.label_Titre_filtre = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Titre_filtre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Titre_filtre.setObjectName("label_Titre_filtre")
    self.gridLayout.addWidget(self.label_Titre_filtre, 0, 2, 1, 1)
    self.label_Bmax = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Bmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Bmax.setObjectName("label_Bmax")
    self.gridLayout.addWidget(self.label_Bmax, 1, 0, 1, 1)
    self.label_Bmax_value_brut = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Bmax_value_brut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Bmax_value_brut.setObjectName("label_Bmax_value_brut")
    self.gridLayout.addWidget(self.label_Bmax_value_brut, 1, 1, 1, 1)
    self.label_Bmax_value_filtre = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Bmax_value_filtre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Bmax_value_filtre.setObjectName("label_Bmax_value_filtre")
    self.gridLayout.addWidget(self.label_Bmax_value_filtre, 1, 2, 1, 1)
    self.label_Hmax = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Hmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Hmax.setObjectName("label_Hmax")
    self.gridLayout.addWidget(self.label_Hmax, 2, 0, 1, 1)
    self.label_Hmax_value_brut = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Hmax_value_brut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Hmax_value_brut.setObjectName("label_Hmax_value_brut")
    self.gridLayout.addWidget(self.label_Hmax_value_brut, 2, 1, 1, 1)
    self.label_Hmax_value_filtre = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Hmax_value_filtre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Hmax_value_filtre.setObjectName("label_Hmax_value_filtre")
    self.gridLayout.addWidget(self.label_Hmax_value_filtre, 2, 2, 1, 1)
    self.label_Br = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Br.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Br.setObjectName("label_Br")
    self.gridLayout.addWidget(self.label_Br, 3, 0, 1, 1)
    self.label_Br_value_brut = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Br_value_brut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Br_value_brut.setObjectName("label_Br_value_brut")
    self.gridLayout.addWidget(self.label_Br_value_brut, 3, 1, 1, 1)
    self.label_Br_value_filtre = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Br_value_filtre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Br_value_filtre.setObjectName("label_Br_value_brut")
    self.gridLayout.addWidget(self.label_Br_value_filtre, 3, 2, 1, 1)
    self.label_Hc = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Hc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Hc.setObjectName("label_Hc")
    self.gridLayout.addWidget(self.label_Hc, 4, 0, 1, 1)
    self.label_Hc_value_brut = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Hc_value_brut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Hc_value_brut.setObjectName("label_Hc_value_brut")
    self.gridLayout.addWidget(self.label_Hc_value_brut, 4, 1, 1, 1)
    self.label_Hc_value_filtre = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Hc_value_filtre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Hc_value_filtre.setObjectName("label_Hc_value_filtre")
    self.gridLayout.addWidget(self.label_Hc_value_filtre, 4, 2, 1, 1)
    self.label_Area = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Area.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Area.setObjectName("label_Area")
    self.gridLayout.addWidget(self.label_Area, 5, 0, 1, 1)
    self.label_Area_value_brut = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Area_value_brut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Area_value_brut.setObjectName("label_Area_value_brut")
    self.gridLayout.addWidget(self.label_Area_value_brut, 5, 1, 1, 1)
    self.label_Area_value_filtre = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Area_value_filtre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Area_value_filtre.setObjectName("label_Area_value_filtre")
    self.gridLayout.addWidget(self.label_Area_value_filtre, 5, 2, 1, 1)
    self.label_Pv = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Pv.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Pv.setObjectName("label_Pv")
    self.gridLayout.addWidget(self.label_Pv, 6, 0, 1, 1)
    self.label_Pv_value_brut = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Pv_value_brut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Pv_value_brut.setObjectName("label_Pv_value_brut")
    self.gridLayout.addWidget(self.label_Pv_value_brut, 6, 1, 1, 1)
    self.label_Pv_value_filtre = QtWidgets.QLabel(self.gridLayoutWidget)
    self.label_Pv_value_filtre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.label_Pv_value_filtre.setObjectName("label_Pv_value_filtre")
    self.gridLayout.addWidget(self.label_Pv_value_filtre, 6, 2, 1, 1)
    
    self.groupBox = QtWidgets.QGroupBox(analyse_fft_bh)
    self.groupBox.setGeometry(QtCore.QRect(600, 700, 235, 350))
    self.groupBox.setObjectName("groupBox")
    self.groupBox = QtWidgets.QGroupBox(analyse_fft_bh)
    self.groupBox.setGeometry(QtCore.QRect(835, 700, 145, 350))
    self.groupBox.setObjectName("groupBox")
    self.groupBox = QtWidgets.QGroupBox(analyse_fft_bh)
    self.groupBox.setGeometry(QtCore.QRect(980, 700, 145, 350))
    self.groupBox.setObjectName("groupBox")
    
    self.retranslateUi(analyse_fft_bh)
    QtCore.QMetaObject.connectSlotsByName(analyse_fft_bh)

  def retranslateUi(self, analyse_fft_bh):
    _translate = QtCore.QCoreApplication.translate
    self.label_Harmo.setText(_translate("analyse_fft_bh", "Nombres d'harmoniques filtrage'"))
    analyse_fft_bh.setWindowTitle(_translate("analyse_fft_bh", "Dialog"))
    self.label_Titre_brut.setText(_translate("analyse_fft_bh","Brut"))
    self.label_Titre_filtre.setText(_translate("analyse_fft_bh","Filtré"))
    self.label_Bmax.setText(_translate("analyse_fft_bh", "Bmax (T):"))
    self.label_Bmax_value_brut.setText(_translate("analyse_fft_bh", "0.0"))
    self.label_Bmax_value_filtre.setText(_translate("analyse_fft_bh", "0.0"))
    self.label_Hmax.setText(_translate("analyse_fft_bh", "Hmax (A/m):"))
    self.label_Hmax_value_brut.setText(_translate("analyse_fft_bh", "0.0"))
    self.label_Hmax_value_filtre.setText(_translate("analyse_fft_bh", "0.0"))
    self.label_Br.setText(_translate("analyse_fft_bh", "Br (T):"))
    self.label_Br_value_brut.setText(_translate("analyse_fft_bh", "0.0"))
    self.label_Br_value_filtre.setText(_translate("analyse_fft_bh", "0.0"))
    self.label_Hc.setText(_translate("analyse_fft_bh", "Hc (A/m):"))
    self.label_Hc_value_brut.setText(_translate("analyse_fft_bh", "0.0"))
    self.label_Hc_value_filtre.setText(_translate("analyse_fft_bh", "0.0"))
    self.label_Area.setText(_translate("analyse_fft_bh", "Area (J/m3):"))
    self.label_Area_value_brut.setText(_translate("analyse_fft_bh", "0.0"))
    self.label_Area_value_filtre.setText(_translate("analyse_fft_bh", "0.0"))
    self.label_Pv.setText(_translate("analyse_fft_bh", "Pv (W/m3):"))
    self.label_Pv_value_brut.setText(_translate("analyse_fft_bh", "0.0"))
    self.label_Pv_value_filtre.setText(_translate("analyse_fft_bh", "0.0"))
    self.clear_button.setText(_translate("analyse_fft_bh", "Effacer les courbes"))
    
    self.toolButton_Save.setText(_translate("analyse_fft_bh", "Enregistrer la courbe filtree"))
    
    self.Start_filtrage_button.setText(_translate("analyse_fft_bh", "Start filtrage"))
  
    
    