# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'curve_comparaison.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_curve_comparaison(object):
    def setupUi(self, curve_comparaison):
        curve_comparaison.setObjectName("curve_comparaison")
        curve_comparaison.resize(798, 745)
        self.import_button = QtWidgets.QPushButton(curve_comparaison)
        self.import_button.setGeometry(QtCore.QRect(600, 170, 181, 25))
        self.import_button.setObjectName("import_button")
        self.clear_button = QtWidgets.QPushButton(curve_comparaison)
        self.clear_button.setGeometry(QtCore.QRect(600, 200, 181, 25))
        self.clear_button.setObjectName("clear_button")
        self.export_table_button = QtWidgets.QPushButton(curve_comparaison)
        self.export_table_button.setGeometry(QtCore.QRect(600, 320, 181, 25))
        self.export_table_button.setObjectName("export_table_button")
        self.tableWidget = QtWidgets.QTableWidget(curve_comparaison)
        self.tableWidget.setGeometry(QtCore.QRect(10, 500, 771, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.widget_cpr = MplWidget(curve_comparaison)
        self.widget_cpr.setGeometry(QtCore.QRect(10, 10, 571, 461))
        self.widget_cpr.setObjectName("widget_cpr")
        self.colors_button = QtWidgets.QPushButton(curve_comparaison)
        self.colors_button.setGeometry(QtCore.QRect(600, 230, 181, 25))
        self.colors_button.setObjectName("colors_button")
        self.remove_row_button = QtWidgets.QPushButton(curve_comparaison)
        self.remove_row_button.setGeometry(QtCore.QRect(600, 290, 181, 25))
        self.remove_row_button.setObjectName("remove_row_button")
        self.add_row_button = QtWidgets.QPushButton(curve_comparaison)
        self.add_row_button.setGeometry(QtCore.QRect(600, 260, 181, 25))
        self.add_row_button.setObjectName("add_row_button")

        self.retranslateUi(curve_comparaison)
        QtCore.QMetaObject.connectSlotsByName(curve_comparaison)

    def retranslateUi(self, curve_comparaison):
        _translate = QtCore.QCoreApplication.translate
        curve_comparaison.setWindowTitle(_translate("curve_comparaison", "Dialog"))
        self.import_button.setText(_translate("curve_comparaison", "Sélectionner les courbes"))
        self.clear_button.setText(_translate("curve_comparaison", "Effacer les courbes"))
        self.export_table_button.setText(_translate("curve_comparaison", "Exporter la table"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("curve_comparaison", "Nom fichier"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("curve_comparaison", "Bmax", "1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("curve_comparaison", "Fréquence"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("curve_comparaison", "Hc"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("curve_comparaison", "Br"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("curve_comparaison", "Hmax"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("curve_comparaison", "μᵣ"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("curve_comparaison", "W (J/m³)"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("curve_comparaison", "P (W/m³)"))
        self.colors_button.setText(_translate("curve_comparaison", "Changer les couleurs"))
        self.remove_row_button.setText(_translate("curve_comparaison", "Enlever une ligne"))
        self.add_row_button.setText(_translate("curve_comparaison", "Ajouter une ligne"))
from mplwidget import MplWidget
