# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_notes(object):
    def setupUi(self, notes):
        notes.setObjectName("notes")
        notes.resize(684, 575)
        self.verticalLayoutWidget = QtWidgets.QWidget(notes)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 661, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(notes)
        self.buttonBox.rejected.connect(notes.close) # type: ignore
        self.buttonBox.accepted.connect(notes.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(notes)

    def retranslateUi(self, notes):
        _translate = QtCore.QCoreApplication.translate
        notes.setWindowTitle(_translate("notes", "Dialog"))
