# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pertesvsfreq.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mplwidget import MplWidget


class Ui_PertesVsFreq(object):
    def setupUi(self, PertesVsFreq):
        PertesVsFreq.setObjectName("PertesVsFreq")
        PertesVsFreq.resize(822, 678)
        self.buttonBox = QtWidgets.QDialogButtonBox(PertesVsFreq)
        self.buttonBox.setGeometry(QtCore.QRect(440, 630, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = MplWidget(PertesVsFreq)
        self.widget.setGeometry(QtCore.QRect(10, 10, 571, 461))
        self.widget.setObjectName("widget")
        self.import_button = QtWidgets.QPushButton(PertesVsFreq)
        self.import_button.setGeometry(QtCore.QRect(640, 120, 89, 25))
        self.import_button.setObjectName("import_button")
        self.import_list = QtWidgets.QListWidget(PertesVsFreq)
        self.import_list.setGeometry(QtCore.QRect(10, 480, 551, 181))
        self.import_list.setObjectName("import_list")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(PertesVsFreq)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(580, 180, 232, 271))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.pertes_SpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.pertes_SpinBox.setMaximum(999999.99)
        self.pertes_SpinBox.setObjectName("pertes_SpinBox")
        self.gridLayout.addWidget(self.pertes_SpinBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.freq_SpinBox_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.freq_SpinBox_2.setMaximum(999999.99)
        self.freq_SpinBox_2.setObjectName("freq_SpinBox_2")
        self.gridLayout.addWidget(self.freq_SpinBox_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.point_Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.point_Button.setObjectName("point_Button")
        self.gridLayout_3.addWidget(self.point_Button, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.curve_Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.curve_Button.setObjectName("curve_Button")
        self.horizontalLayout.addWidget(self.curve_Button)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.valider_Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.valider_Button.setObjectName("valider_Button")
        self.gridLayout_3.addWidget(self.valider_Button, 4, 0, 1, 1)
        self.actionimport = QtWidgets.QAction(PertesVsFreq)
        self.actionimport.setObjectName("actionimport")
        self.actionNewCurve = QtWidgets.QAction(PertesVsFreq)
        self.actionNewCurve.setObjectName("actionNewCurve")
        self.actionNewPoint = QtWidgets.QAction(PertesVsFreq)
        self.actionNewPoint.setObjectName("actionNewPoint")
        self.actionValider = QtWidgets.QAction(PertesVsFreq)
        self.actionValider.setObjectName("actionValider")

        self.retranslateUi(PertesVsFreq)
        self.buttonBox.accepted.connect(PertesVsFreq.accept) # type: ignore
        self.buttonBox.rejected.connect(PertesVsFreq.reject) # type: ignore
        self.import_button.clicked.connect(self.actionimport.trigger) # type: ignore
        self.point_Button.clicked.connect(self.actionNewPoint.trigger) # type: ignore
        self.curve_Button.clicked.connect(self.actionNewCurve.trigger) # type: ignore
        self.valider_Button.clicked.connect(self.actionValider.trigger) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PertesVsFreq)

    def retranslateUi(self, PertesVsFreq):
        _translate = QtCore.QCoreApplication.translate
        PertesVsFreq.setWindowTitle(_translate("PertesVsFreq", "Pertes vs Fréquences"))
        self.import_button.setText(_translate("PertesVsFreq", "Importer"))
        self.label_4.setText(_translate("PertesVsFreq", "kHz"))
        self.label_2.setText(_translate("PertesVsFreq", "Fréquence :"))
        self.label_3.setText(_translate("PertesVsFreq", "W/m³"))
        self.label.setText(_translate("PertesVsFreq", "Pertes :"))
        self.point_Button.setText(_translate("PertesVsFreq", "Ajouter point"))
        self.curve_Button.setText(_translate("PertesVsFreq", "Nouvelle courbe"))
        self.valider_Button.setText(_translate("PertesVsFreq", "Valider"))
        self.actionimport.setText(_translate("PertesVsFreq", "import"))
        self.actionNewCurve.setText(_translate("PertesVsFreq", "NewCurve"))
        self.actionNewPoint.setText(_translate("PertesVsFreq", "NewPoint"))
        self.actionValider.setText(_translate("PertesVsFreq", "Valider"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PertesVsFreq = QtWidgets.QDialog()
    ui = Ui_PertesVsFreq()
    ui.setupUi(PertesVsFreq)
    PertesVsFreq.show()
    sys.exit(app.exec_())
